name: Bug Report
description: Create a report to help us improve
title: ""
labels: [bug]
assignees: ""
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if any issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what you're experiencing.
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: Please provide your operating system, browser, and browser version.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
